import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  DATABASE_URL: Joi.string().uri().required(),
  REDIS_URL: Joi.string().uri().required(),
  JWT_SECRET: Joi.string().min(16).required(),
  JWT_EXPIRES_IN: Joi.string().default('7d'),
  ENCRYPTION_KEY: Joi.string().min(16).required(),
  PORT: Joi.number().default(3001),
  CORS_ORIGIN: Joi.string().required(),
  META_API_VERSION: Joi.string().default('v21.0'),
  GOOGLE_ADS_DEVELOPER_TOKEN: Joi.string().optional(),
  GOOGLE_ADS_CLIENT_ID: Joi.string().optional(),
  GOOGLE_ADS_CLIENT_SECRET: Joi.string().optional(),
  GOOGLE_ADS_REFRESH_TOKEN: Joi.string().optional(),
  GOOGLE_ADS_LOGIN_CUSTOMER_ID: Joi.string().optional(),
  GOOGLE_ADS_API_VERSION: Joi.string().default('v21'),
  DEFAULT_PROJECT_RATE_LIMIT_PER_MINUTE: Joi.number().default(120),
  BODY_LIMIT: Joi.string().default('100kb'),
  GLOBAL_ORIGIN_WHITELIST: Joi.string().allow('').optional(),
  GIT_COMMIT: Joi.string().optional(),
  BUILD_DATE: Joi.string().optional(),
  GEOIP_ENABLED: Joi.boolean().default(true),
  GEOIP_DB_PATH: Joi.string().optional(),
  GEOIP_CACHE_TTL_SECONDS: Joi.number().default(86400),
  ENABLE_TRACKER: Joi.boolean().default(true),
  ENABLE_FORWARDING: Joi.boolean().default(true),
  ENABLE_GOOGLE_ADS: Joi.boolean().default(true),
  ENABLE_META_CAPI: Joi.boolean().default(true),
  ENABLE_GA4: Joi.boolean().default(true),
  ENABLE_WEBHOOKS: Joi.boolean().default(true),
  ENABLE_SWAGGER: Joi.boolean().default(true),
  ENABLE_METRICS: Joi.boolean().default(true),
  ENABLE_HEALTH: Joi.boolean().default(true),
});
