export const FEATURE_FLAGS = {
  TRACKER: 'ENABLE_TRACKER',
  FORWARDING: 'ENABLE_FORWARDING',
  GOOGLE_ADS: 'ENABLE_GOOGLE_ADS',
  META_CAPI: 'ENABLE_META_CAPI',
  GA4: 'ENABLE_GA4',
  WEBHOOKS: 'ENABLE_WEBHOOKS',
  SWAGGER: 'ENABLE_SWAGGER',
  METRICS: 'ENABLE_METRICS',
  HEALTH: 'ENABLE_HEALTH',
} as const;

export type FeatureFlag = (typeof FEATURE_FLAGS)[keyof typeof FEATURE_FLAGS];
